name=CoolSpotGame
version=1.0.0
author=YourName
maintainer=YourName
sentence=Cool Spot Game for Brenton OS
paragraph=A platformer game based on the 90s classic.
category=Game
url=
architectures=esp32
